PYIC-3510: Correlate data for F2F VC
govuk-one-login/ipv-core-back pull request #1181
Opened 2023-09-06 14:58 UTC by Wynndow

## Proposed changes

### What changed

Correlate data for F2F VC

### Why did it change

The f2f VC is collected async. We weren't doing the usual checks on the data in contains to be sure it correlates with the data in the other VCs. This meant data was being sent to SPoT that was being rejected.

This change will do the correlation in the check-existing-identity lambda and send the user to the F2F fail page if the data doesn't match. The user will then have the opportunity to reset their identity.

We don't need to take any action of the data doesn't correlate if we're not on an F2F journey. This is an expected scenario and will be picked up by them not matching a profile and be sent to the reset-journey lambda separately.

This also moves the call to updateVcStatues higher in the handler so it's available for the correlation check. This way the F2F VC is included.

### Issue tracking

- [PYIC-3510](https://govukverify.atlassian.net/browse/PYIC-3510)

2023-09-06 15:50 UTC, therealslimsladey requested changes
minor items

2023-09-06 15:50 UTC, therealslimsladey commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +            LOGGER.error("Failed to correlate names");
Structured messages with StringMapMessage are preferred?

2023-09-06 15:50 UTC, therealslimsladey commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +            LOGGER.error("Failed to correlate birth dates");
Structured messages with StringMapMessage are preferred?

2023-09-06 15:53 UTC, Wynndow commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +            LOGGER.error("Failed to correlate birth dates");
I'm not sure they actually add much in this scenario though, other than making the data harder to see. Makes sense if you're logging discreet data about something you might want to search on. Like "how many log messages where ci-score >= 5". But this is just info.

2023-09-06 16:02 UTC, therealslimsladey commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +            LOGGER.error("Failed to correlate names");
Discussed and discounted

2023-09-06 16:36 UTC, therealslimsladey commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +        } catch (NoVcStatusForIssuerException e) {
Test?

2023-09-06 16:36 UTC, therealslimsladey commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +        if (!userIdentityService.checkBirthDateCorrelationInCredentials(
Test?

2023-09-07 07:29 UTC, Wynndow commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +        } catch (NoVcStatusForIssuerException e) {
Whoops - have added. Good catch.

2023-09-07 07:30 UTC, Wynndow commented on lambdas/check-existing-identity/src/main/java/uk/gov/di/ipv/core/checkexistingidentity/CheckExistingIdentityHandler.java
> +        if (!userIdentityService.checkBirthDateCorrelationInCredentials(
Oh snap. I have `shouldReturnFailResponseForFaceToFaceIfBirthDatesDoNotCorrelate` but it's actually not testing it at all. Will fix up.

2023-09-07 08:55 UTC, therealslimsladey approved these changes
lgtm

2023-09-07 09:01 UTC, merged