PYIC-3669: Add CredentialEvidenceItemTest
govuk-one-login/ipv-core-back pull request #1244
Opened 2023-10-05 13:34 UTC by MikeCollingwood

## Proposed changes

### What changed

- Added CredentialEvidenceItemTest

### Why did it change

### Issue tracking

- [PYIC-3669](https://govukverify.atlassian.net/browse/PYIC-3669)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

2023-10-06 08:47 UTC, MikeCollingwood commented
NB: Reaches 92% coverage locally, with branch coverage

2023-10-06 09:57 UTC, TalatAydinGDS requested changes
I cannot see code coverage and Sonarqube report on GitHub. Please ask to SRE team, there might be an issue. We need to see what review code coverage and Sonar feedback.

2023-10-06 09:57 UTC, TalatAydinGDS commented on libs/gpg45-evaluator/src/test/java/uk/gov/di/ipv/core/library/gpg45/domain/CredentialEvidenceItemTest.java
> +import static org.junit.jupiter.api.Assertions.*;
We don't use '*' and add only needs dependency.

2023-10-06 09:57 UTC, TalatAydinGDS commented on libs/gpg45-evaluator/src/test/java/uk/gov/di/ipv/core/library/gpg45/domain/CredentialEvidenceItemTest.java
> +        CredentialEvidenceItem credentialEvidenceItem1 =
I think, you can create a method or can use ParameterizedTest here. There are so many duplicate code here.

2023-10-06 09:57 UTC, TalatAydinGDS commented on libs/gpg45-evaluator/src/test/java/uk/gov/di/ipv/core/library/gpg45/domain/CredentialEvidenceItemTest.java
> +                new CredentialEvidenceItem(EvidenceType.ACTIVITY, 30, Collections.emptyList());
I think, can use builder()

2023-10-06 09:57 UTC, TalatAydinGDS commented on libs/gpg45-evaluator/src/test/java/uk/gov/di/ipv/core/library/gpg45/domain/CredentialEvidenceItemTest.java
> +        CredentialEvidenceItem credentialEvidenceItem1 = new CredentialEvidenceItem(10, 20, null);
I think, if we are not writing constructor test, I think using a builder() would be a great choice.

2023-10-09 13:10 UTC, TalatAydinGDS approved these changes
LGTM

2023-10-10 08:18 UTC, merged