PYIC-4089: Send f2f reset identity confirmation email
govuk-one-login/ipv-core-back pull request #1553
Opened 2024-01-19 14:43 UTC by shivanshuit914

## Proposed changes

- Send f2f reset identity confirmation email

### What changed

-  Sending f2f reset identity confirmation email to user when initiated buy user.

### Why did it change

- To notify user

### Issue tracking

- [PYIC-4089](https://govukverify.atlassian.net/browse/PYIC-4089)

[PYIC-4089]: https://govukverify.atlassian.net/browse/PYIC-4089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-22 10:20 UTC, DanCorderIPV requested changes

2024-01-22 10:20 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
Why limit this to the fraud VC for F2F?

2024-01-22 10:20 UTC, DanCorderIPV commented on lambdas/reset-identity/src/test/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandlerTest.java
> +import uk.gov.di.ipv.core.library.domain.*;
I don't think we allow `*` imports?

2024-01-22 10:20 UTC, DanCorderIPV commented on libs/email-service/src/main/java/uk/gov/di/ipv/core/library/service/EmailService.java
> +        sendUserTriggeredIdentityResetConfirmation(
I wouldn't combine these like this. At the moment they have the same personalisation, but there's no guarantee things will stay that way. I'd copy `sendUserTriggeredIdentityResetConfirmation` and just change the template parameter.

2024-01-22 10:20 UTC, DanCorderIPV commented on libs/email-service/src/main/java/uk/gov/di/ipv/core/library/service/EmailService.java
>          // hardcoded
If you do leave things like they are now, then this comment doesn't make sense any more as the template IDs are being hardcoded in the other methods.

2024-01-22 10:20 UTC, DanCorderIPV commented on lambdas/reset-identity/src/test/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandlerTest.java
> +import uk.gov.di.ipv.core.library.domain.*;
and in other files too

2024-01-22 10:27 UTC, shivanshuit914 commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
No particular reason thought we can get user full name from fraud CRI as we have verified fraud score, I was thinking to use F2F one but in this journey F2F will be pending so we can't get users details from evidence. Do you suggest any other CRI that we should use here ?

2024-01-22 10:35 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
The code that's already there will just check all VCs to find a name I think? If the fraud VC isn't special then can you just re-use what's already there?

2024-01-22 10:41 UTC, DanCorderIPV commented on libs/common-services/src/main/java/uk/gov/di/ipv/core/library/config/ConfigurationVariable.java
> +            "self/govUkNotify/emailTemplates/FaceToFaceIdentityResetConfirmation");
Also could you change this to `self/govUkNotify/emailTemplates/UserTriggeredIdentityResetConfirmationF2f` to match PR 4090 please?

2024-01-22 10:55 UTC, shivanshuit914 commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
yes 👍

2024-01-22 14:59 UTC, shivanshuit914 commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
I tried to use `findIdentityClaim` and found `isEvidenceVc` return false for all VcItems. may be because verification is still pending.

2024-01-23 11:56 UTC, DanCorderIPV requested changes

2024-01-23 11:56 UTC, DanCorderIPV commented on libs/email-service/src/main/java/uk/gov/di/ipv/core/library/service/EmailService.java
> +                        "Attempting to send user triggered identity reset confirmation email"));
Please update to include F2F

2024-01-23 11:56 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                                clientOAuthSessionItem.getUserId(), FRAUD_CRI);
I've chatted to Joe about this as using the Fraud VC seems fragile to future journey map changes.
Could you please instead add an overload of `UserIdentityService.findIdentityClaim()` that takes a flag to indicate whether to only use evidenceVCs or all VCs (and default the flag to the current behaviour).
Then you can update the old `ResetIdentityHandler.getUserName()` to `ResetIdentityHandler.getUnconfirmedUserName()` and use that for both emails.

2024-01-23 12:32 UTC, blakeyp commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +            CriResponseItem f2fRequest = criResponseService.getFaceToFaceRequest(userId);
Just thinking do we _need_ to retrieve the pending F2F request here? Could we use `lambdaInput` in the journey map with a specific state for this route (from the F2F pending page)? something like
```
RESET_IDENTITY_USER_INITIATED_F2F:
  response:
    type: process
    lambda: reset-identity
    lambdaInput:
      isUserInitiatedF2f: true
  events:
    next:
      ...
```

2024-01-23 14:25 UTC, shivanshuit914 commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +            CriResponseItem f2fRequest = criResponseService.getFaceToFaceRequest(userId);
Yes, need to retrieve the pending F2F request to make sure we sending correct email f2f or without f2f.

2024-01-23 15:42 UTC, shivanshuit914 commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +            CriResponseItem f2fRequest = criResponseService.getFaceToFaceRequest(userId);
I tried this, it requires we need to add both lambda input all places, its not optional  like

```
RESET_IDENTITY_USER_INITIATED_F2F:
  response:
    type: process
    lambda: reset-identity
    lambdaInput:
      isUserInitiatedF2f: true
      isUserInitiated: false
```

2024-01-23 17:34 UTC, blakeyp commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +            CriResponseItem f2fRequest = criResponseService.getFaceToFaceRequest(userId);
Hmm ok that's not ideal, let's stick with the current approach

2024-01-24 10:36 UTC, DanCorderIPV requested changes

2024-01-24 10:36 UTC, DanCorderIPV commented on libs/user-identity-service/src/main/java/uk/gov/di/ipv/core/library/service/UserIdentityService.java
> +                if ((checkEvidence
This seems simpler?
```
if ((!checkEvidence || isEvidenceVc(vcStoreItem))
    && VcHelper.isSuccessfulVc(SignedJWT.parse(vcStoreItem.getCredential()))) {
```

2024-01-24 10:36 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +    private String getUserName(List<VcStoreItem> credentials, boolean checkEvidence) {
As before, please rename this to `getUnconfirmedUserName()` and remove the `checkEvidence` flag from here too. This method should always pass `false` to `findIdentityClaim()`

2024-01-24 10:36 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +                emailService.sendUserTriggeredF2FIdentityResetConfirmation(
This is the only different line between these two block, please combine them

2024-01-24 10:36 UTC, DanCorderIPV commented on lambdas/reset-identity/src/main/java/uk/gov/di/ipv/core/resetidentity/ResetIdentityHandler.java
> +            if (isUserInitiated && f2fRequest == null) {
Once you update `getUserName()` there will be no difference here between F2F and non-F2F so these blocks can be combined.

2024-01-24 14:17 UTC, DanCorderIPV approved these changes

2024-01-24 14:18 UTC, merged