PYIC-3903: Add ticf cri pact test
govuk-one-login/ipv-core-back pull request #1653
Opened 2024-02-19 11:29 UTC by MikeCollingwood

## Proposed changes

### What changed

- Added pact test for ticf cri

### Why did it change

- To contract test the service interaction for this specific endpoint

### Issue tracking

- [PYIC-3903](https://govukverify.atlassian.net/browse/PYIC-3903)
- [FPAD-2225](https://govukverify.atlassian.net/browse/FPAD-2225)

2024-02-20 16:06 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/helpers/JwtTestHelper.java
> +package uk.gov.di.ipv.core.callticfcri.helpers;
I've recently merged a change into main that puts this kind of shared PACT testing code into its own library in `libs`. Could you merge main into your branch and add `readFile` to the lib version?

2024-02-20 16:06 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                            body.minArrayLike(
Why use `minArrayLike` here instead of just `array` (or `minMaxArray`)

2024-02-20 16:06 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                            body.minArrayLike("vtr", 1, PactDslJsonRootValue.stringType("P2"), 1);
Should TICF ever return more than one `vtr`?

2024-02-20 16:06 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +    public RequestResponsePact requestForUserWithNoInterventions(PactDslWithProvider builder) {
Naming these is tricky, but I think I'd go for something more like `validPassportVcReturnsVcWithNoInterventions()`

2024-02-20 16:06 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/resources/dvlaVc/body.json
> +{
It's nice for viewing and editing this data that it's in a JSON file, but it does mean that we can't comment things like the `nbf` and `exp` fields, or point people towards how to generate valid signatures.
No need to change all this right now as having the data in the test class is also not ideal. Hopefully we can come up with a better way and apply it to all the tests.

2024-02-21 10:10 UTC, MikeCollingwood commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                            body.minArrayLike("vtr", 1, PactDslJsonRootValue.stringType("P2"), 1);
I think it can as it might be used to risk assess non-P2 profiles, e.g. ["P2", "PCL250"] - have checked with Joe

2024-02-21 14:03 UTC, Joe-Edwards-GDS commented on libs/pact-test-helpers/src/main/java/uk/gov/di/ipv/core/library/pacttesthelpers/PactJwtBuilder.java
> +        return FileUtils.readFileToString(new File(path.toUri()), StandardCharsets.UTF_8);
I think it's generally best practice to load these as resources, rather than files - which also means you don't need to provide a full path (it'll be relative to the resources directory).

You might want something like:
```
IOUtils.resourceToString("dvlaVc/body.json", StandardCharsets.UTF_8);
```

This has a couple of benefits:
- the tests can be run as compiled code, without relying on the source structure (e.g. you could build a tests JAR and execute that)
- the path is less ambiguous and less fragile - it doesn't rely on the working directory that the tests are being executed from, you know it must be provided as a 'resource'

2024-02-28 10:29 UTC, Joe-Edwards-GDS commented on lambdas/call-ticf-cri/build.gradle
> +			"au.com.dius.pact.consumer:junit5:4.6.5",
I don't think this should be a production dependency!

2024-02-28 10:30 UTC, DanCorderIPV requested changes

2024-02-28 10:30 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                        "TICF VC is signed with {\"kty\":\"EC\",\"d\":\"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU\",\"crv\":\"P-256\",\"x\":\"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM\",\"y\":\"K
Not sure we need this - we do need to know that our example VC is signed with this key, but the TICF signature will be ignored in the tests.

2024-02-28 10:30 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                .given("TICF VC risk assessment has id riskAssessmentId")
`riskAssessmentId` -> `dummyRiskAssessmentId` ?

2024-02-28 10:30 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                .given("TICF timeouts")
Minor but `timeouts` sounds very odd to me, maybe `times out`?

2024-02-28 10:30 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                .given("TICF VC risk assessment has id riskAssessmentId")
`riskAssessmentId` -> `dummyRiskAssessmentId`?

2024-02-28 10:30 UTC, DanCorderIPV commented on lambdas/call-ticf-cri/src/test/java/uk/gov/di/ipv/core/callticfcri/pact/ticfCri/ContractTest.java
> +                .given("TICF VC risk assessment has id riskAssessmentId")
and below

2024-02-28 11:45 UTC, DanCorderIPV approved these changes

2024-02-28 11:54 UTC, merged