WIP
govuk-one-login/ipv-core-back pull request #2571
Opened 2024-10-09 15:06 UTC by AmritSidhu

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [PYIC-XXXX](https://govukverify.atlassian.net/browse/PYIC-XXXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2024-10-10 14:45 UTC, DanCorderIPV requested changes

2024-10-10 14:45 UTC, DanCorderIPV commented on api-tests/features/p1-journeys.feature
> +  Scenario: P1 F2F Low confidence journey should have relevent photoid option text
Is this test needed? We're not testing any text and the test steps are just a subset of `P1 F2F Journey` above

2024-10-10 14:45 UTC, DanCorderIPV commented on api-tests/features/p1-journeys.feature
> +  Scenario: P1 F2F Support low strength F2F documents for thin file users
I realise that you've probably just copied this test name over from an end to end test, but there's no KBV step here so I'm not sure what `thin file` has to do with this test.

2024-10-10 16:08 UTC, blakeyp commented on api-tests/features/p1-journeys.feature
> +  Scenario: P1 F2F Support low strength F2F documents for thin file users
I think this is referring to thin _fraud_ file - when a user has a low fraud/activity score and we need to pass a required strength to F2F CRI

2024-10-10 16:08 UTC, blakeyp commented on api-tests/features/p1-journeys.feature
> +  Scenario: P1 F2F Support low strength F2F documents for thin file users
will be clearer if we just rename it "thin fraud file" users

2024-10-10 16:10 UTC, blakeyp commented on api-tests/features/p1-journeys.feature
> +  Scenario: P1 F2F Support low strength F2F documents for P2 user
This is the regression scenario for P2 but we might already have a pretty identical test to this in the P2 tests? if so I don't think we need this

2024-10-14 10:16 UTC, blakeyp approved these changes

2024-10-14 12:34 UTC, DanCorderIPV approved these changes

2024-10-14 13:09 UTC, merged