Reconfigure API Gateway so that it calls the Lambda using JSON
govuk-one-login/ipv-core-back pull request #830
Opened 2023-05-18 14:42 UTC by TalatAydinGDS

## Proposed changes

### What changed

Reconfigure API Gateway so it calls the build-cri-oauth-request lambda using JSON

### Why did it change

We'll be calling these journey lambdas within the journey engine step function so will be removing API Gateway

### Issue tracking

- [PYIC-2733](https://govukverify.atlassian.net/browse/PYIC-2733)

2023-05-19 08:56 UTC, chris-dco requested changes

2023-05-19 08:56 UTC, chris-dco commented on openAPI/core-back-internal.yaml
> +                "journey": "$input.params('criId')",
As the Step Function will send the full URL e.g. `/journey/cri/build-oauth-request/dcmaw` to the Lambda the API Gateway should do the same. In this case I believe the code you need is.

```json
"journey": "/journey/cri/build-oauth-request/$input.params('criId')"
```

2023-05-19 15:16 UTC, TalatAydinGDS commented on openAPI/core-back-internal.yaml
> +                "journey": "$input.params('criId')",
done

2023-05-22 09:13 UTC, blakeyp approved these changes

2023-05-23 13:39 UTC, chris-dco approved these changes

2023-05-23 13:40 UTC, merged